### ISSUE TITLE
How to access health checks?

### ISSUE THREAD

**Issue by paymog** [dfuse-io/relayer#8]
I see the relayer has a [`healthz`](https://github.com/streamingfast/relayer/blob/develop/healthz.go) file but I can't figure out how to check if the relayer is healthy. 

I see that the [`isReady`](https://github.com/streamingfast/relayer/blob/develop/app/relayer/app.go#L106) function is called by the [http_server](https://github.com/streamingfast/node-manager/blob/develop/operator/http_server.go#L112) but when I try to use `/healthz` as a readiness check

```
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 13011
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 3
      successThreshold: 1
      timeoutSeconds: 1
```

 I get the following

```
  Warning  Unhealthy  2s (x22 over 65s)  kubelet            Readiness probe failed: Get "http://192.168.81.178:13011/healthz": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x00\x00\x06\x04\x00\x00\x00\x00\x00\x00\x05\x00\x00@\x00"
```
